### ISSUE TITLE
Problem with configuration

### ISSUE THREAD

**Issue by Sarah989** [bmuller/pymur#3]
I am trying to configure pymur by following these steps which were posted in pymur's website:

```
cd pymur
./configure 
make
sudo make install
```

However, when I reach this step `./configure ` I get

`checking indri/Index.hpp usability... no`
`checking indri/Index.hpp presence... no`
`checking for indri/Index.hpp... no`
`configure: error: Could not find lemur's header files.`

I tried to including the header files using `CPPFLAGS='-I$HOME/path/to/file' ./configure` but nothing changed. So is it a bug in pymur or am I doing something wrong?

**Comment by bmuller** [comment]
Hey @Sarah989 - this repo hasn't been updated in 8 years and is no longer supported.  If you still want to try to use it - I'd suggest making sure that you have the right path to the Indri include files directory being passed to `-I` in the `CPPFLAGS`.
